# Generated by Django 6.1 on 2026-08-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del portal')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('intra', 'INTRA'), ('orbita', 'Órbita'), ('nom035', 'NOM035'), ('contabilidad', 'Contabilidad'), ('collaboracali', 'Collaboracali')], max_length=30, verbose_name='Categoría')),
                ('icono', models.CharField(default='fa-solid fa-globe', max_length=100, verbose_name='Icono FontAwesome')),
                ('activo', models.BooleanField(default=True, verbose_name='Portal activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portales',
                'ordering': ['nombre'],
            },
        ),
    ]
